const DICTIONARY = {
    en: {
        lang_label: "Language:",
        tagline: "KEEP YOUR PRIVATE CHATS PRIVATE",
        btn_home: "HOME",
        btn_privacy: "ABOUT US",
        btn_compliance: "GLOBAL COMPLIANCE STANDARDS",
        btn_pricing: "PRICING & INSTITUTIONAL TIERS",
        btn_faq: "FAQ",
        btn_support: "EXECUTIVE SUPPORT & CONTACT",
        cta_secure: "ACTIVATE SECURE MODE",
        video_header_badge: "SEARCH YOUR LANGUAGE IN THE VIDEO MENU",
        video_preview_title: "WATCH PRESENTATION",
        video_lang_help: "Select your preferred language above to watch the institutional presentation with native audio.",
        footer_compliance: "Architecture designed in accordance with international compliance standards: GDPR (EU) • COPPA (USA) • UN (General Comment No. 25 — Children's Rights)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR Compliant.",
        about_main_title: "What is BENEATH?",
        about_main_desc: "A cybersecurity tool for private communication without sharing your phone number, email address, or personal data. It is not an entertainment messaging service.",
        about_transmit_title: "Transmit, don’t store (48 / 72 hours)",
        about_transmit_desc: "Messages and files are purged from infrastructure once delivered. Files expire after 48 to 72 hours. Download them before they are gone.",
        about_ideal_title: "Ideal for:",
        about_item_sports: "<strong>Sports Clubs:</strong> Direct and secure messaging.",
        about_item_schools: "<strong>Schools:</strong> Communication between teachers and parents without exposing personal numbers.",
        about_item_companies: "<strong>Companies & Professional Services:</strong> Confidential exchange of documents and data with clients, suppliers, or candidates without exposing personal contact details."
    },
    es: {
        lang_label: "Idioma:",
        tagline: "MANTÉN TUS CHATS PRIVADOS EN PRIVADO",
        btn_home: "INICIO",
        btn_privacy: "ACERCA DE",
        btn_compliance: "ESTÁNDARES DE CUMPLIMIENTO GLOBAL",
        btn_pricing: "PRECIOS Y NIVELES INSTITUCIONALES",
        btn_faq: "PREGUNTAS FRECUENTES",
        btn_support: "SOPORTE EJECUTIVO Y CONTACTO",
        cta_secure: "ACTIVAR MODO SEGURO",
        video_header_badge: "BUSCA TU IDIOMA EN EL MENÚ DEL VIDEO",
        video_preview_title: "VER PRESENTACIÓN",
        video_lang_help: "Selecciona tu idioma preferido arriba para ver la presentación institucional con audio nativo.",
        footer_compliance: "Arquitectura diseñada conforme a estándares de cumplimiento internacional: GDPR (UE) • COPPA (EE. UU.) • ONU (Observación General N.º 25 — Derechos de los Niños)",
        footer_copyright: "© 2026 BENEATH Technologies. | Conforme al GDPR.",
        about_main_title: "¿Qué es BENEATH?",
        about_main_desc: "Una herramienta de ciberseguridad para comunicación privada sin compartir tu número telefónico, correo electrónico o datos personales. No es un servicio de mensajería de entretenimiento.",
        about_transmit_title: "Transmitir, no almacenar (48 / 72 horas)",
        about_transmit_desc: "Los mensajes y archivos se eliminan de la infraestructura una vez entregados. Los archivos caducan después de 48 a 72 horas. Descárgalos antes de que desaparezcan.",
        about_ideal_title: "Ideal para:",
        about_item_sports: "<strong>Clubes Deportivos:</strong> Mensajería directa y segura.",
        about_item_schools: "<strong>Escuelas:</strong> Comunicación entre profesores y padres sin exponer números personales.",
        about_item_companies: "<strong>Empresas y Servicios Profesionales:</strong> Intercambio confidencial de documentos y datos con clientes, proveedores o candidatos sin exponer datos de contacto personal."
    },
    pt: {
        lang_label: "Idioma:",
        tagline: "MANTENHA SEUS CHATS PRIVADOS PRIVADOS",
        btn_home: "INÍCIO",
        btn_privacy: "QUEM SOMOS",
        btn_compliance: "PADRÕES DE CONFORMIDADE GLOBAL",
        btn_pricing: "PREÇOS E NÍVEIS INSTITUCIONAIS",
        btn_faq: "PERGUNTAS FREQUENTES",
        btn_support: "SUPORTE EXECUTIVO E CONTATO",
        cta_secure: "ATIVAR MODO SEGURO",
        video_header_badge: "BUSQUE SEU IDIOMA NO MENU DO VÍDEO",
        video_preview_title: "ASSISTIR APRESENTAÇÃO",
        video_lang_help: "Selecione seu idioma preferido acima para assistir à apresentação institucional com áudio nativo.",
        footer_compliance: "Arquitetura projetada de acordo com padrões internacionais de conformidade: GDPR (UE) • COPPA (EUA) • ONU (Comentário Geral nº 25 — Direitos das Crianças)",
        footer_copyright: "© 2026 BENEATH Technologies. | Compatível com GDPR.",
        about_main_title: "O que é o BENEATH?",
        about_main_desc: "Uma ferramenta de cibersegurança para comunicação privada sem compartilhar seu número de telefone, e-mail ou dados pessoais. Não é um serviço de mensagens de entretenimento.",
        about_transmit_title: "Transmitir, não armazenar (48 / 72 horas)",
        about_transmit_desc: "Mensagens e arquivos são apagados da infraestrutura após a entrega. Os arquivos expiram entre 48 e 72 horas. Baixe-os antes que desapareçam.",
        about_ideal_title: "Ideal para:",
        about_item_sports: "<strong>Clubes Esportivos:</strong> Mensagens diretas e seguras.",
        about_item_schools: "<strong>Escolas:</strong> Comunicação entre professores e pais sem expor números pessoais.",
        about_item_companies: "<strong>Empresas e Serviços Profissionais:</strong> Troca confidencial de documentos e dados com clientes, fornecedores ou candidatos sem expor contatos pessoais."
    },
    fr: {
        lang_label: "Langue :",
        tagline: "GARDEZ VOS DISCUSSIONS PRIVÉES PRIVÉES",
        btn_home: "ACCUEIL",
        btn_privacy: "À PROPOS",
        btn_compliance: "NORMES DE CONFORMITÉ MONDIALE",
        btn_pricing: "TARIFS ET NIVEAUX INSTITUTIONNELS",
        btn_faq: "FAQ",
        btn_support: "SUPPORT EXÉCUTIF ET CONTACT",
        cta_secure: "ACTIVER LE MODE SÉCURISÉ",
        video_header_badge: "CHERCHEZ VOTRE LANGUE DANS LE MENU VIDÉO",
        video_preview_title: "REGARDER LA PRÉSENTATION",
        video_lang_help: "Sélectionnez votre langue préférée ci-dessus pour visionner la présentation institutionnelle avec un audio natif.",
        footer_compliance: "Architecture conçue conformément aux normes de conformité internationale : RGPD (UE) • COPPA (USA) • ONU (Observation générale n° 25 — Droits des enfants)",
        footer_copyright: "© 2026 BENEATH Technologies. | Conforme au RGPD.",
        about_main_title: "Qu'est-ce que BENEATH ?",
        about_main_desc: "Un outil de cybersécurité pour la communication privée sans partage de numéro de téléphone, d'e-mail ou de données personnelles. Ce n'est pas un service de messagerie de divertissement.",
        about_transmit_title: "Transmettre, ne pas stocker (48 / 72 heures)",
        about_transmit_desc: "Les messages et fichiers sont purgés de l'infrastructure une fois livrés. Les fichiers expirent après 48 à 72 heures. Téléchargez-les avant qu'ils ne disparaissent.",
        about_ideal_title: "Idéal pour :",
        about_item_sports: "<strong>Clubs Sportifs :</strong> Messagerie directe et sécurisée.",
        about_item_schools: "<strong>Écoles :</strong> Communication entre enseignants et parents sans exposer les numéros personnels.",
        about_item_companies: "<strong>Entreprises et Services Professionnels :</strong> Échange confidentiel de documents et de données avec les clients, fournisseurs ou candidats sans exposer les coordonnées personnelles."
    },
    de: {
        lang_label: "Sprache:",
        tagline: "HALTEN SIE IHRE PRIVATEN CHATS PRIVAT",
        btn_home: "STARTSEITE",
        btn_privacy: "ÜBER UNS",
        btn_compliance: "GLOBALE COMPLIANCE-STANDARDS",
        btn_pricing: "PREISE & INSTITUTIONELLE STUFEN",
        btn_faq: "FAQ",
        btn_support: "EXECUTIVE-SUPPORT & KONTAKT",
        cta_secure: "SICHEREN MODUS AKTIVIEREN",
        video_header_badge: "SUCHEN SIE IHRE SPRACHE IM VIDEO-MENÜ",
        video_preview_title: "PRÄSENTATION ANSEHEN",
        video_lang_help: "Wählen Sie oben Ihre bevorzugte Sprache aus, um die institutionelle Präsentation mit Originalton anzusehen.",
        footer_compliance: "Architektur entworfen in Übereinstimmung mit internationalen Compliance-Standards: GDPR (EU) • COPPA (USA) • UN (Allgemeiner Kommentar Nr. 25 — Rechte von Kindern)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR-konform.",
        about_main_title: "Was ist BENEATH?",
        about_main_desc: "Ein Cybersicherheits-Tool für private Kommunikation ohne Weitergabe von Telefonnummer, E-Mail-Adresse oder persönlichen Daten. Es ist kein Unterhaltungs-Messaging-Dienst.",
        about_transmit_title: "Übertragen, nicht speichern (48 / 72 Stunden)",
        about_transmit_desc: "Nachrichten und Dateien werden nach der Zustellung aus der Infrastruktur gelöscht. Dateien laufen nach 48 bis 72 Stunden ab. Laden Sie sie herunter, bevor sie weg sind.",
        about_ideal_title: "Ideal für:",
        about_item_sports: "<strong>Sportvereine:</strong> Direkte und sichere Messaging-Kommunikation.",
        about_item_schools: "<strong>Schulen:</strong> Kommunikation zwischen Lehrern und Eltern ohne Offenlegung persönlicher Nummern.",
        about_item_companies: "<strong>Unternehmen & Professionelle Dienste:</strong> Vertraulicher Austausch von Dokumenten und Daten mit Kunden, Lieferanten oder Bewerbern ohne Offenlegung persönlicher Kontaktdaten."
    },
    ko: {
        lang_label: "언어:",
        tagline: "비공개 채팅을 비공개로 유지하세요",
        btn_home: "홈",
        btn_privacy: "회사 소개",
        btn_compliance: "글로벌 규정 준수 표준",
        btn_pricing: "가격 및 기관 등급",
        btn_faq: "자주 묻는 질문",
        btn_support: "임원 지원 및 연락처",
        cta_secure: "보안 모드 활성화",
        video_header_badge: "동영상 메뉴에서 언어를 검색하세요",
        video_preview_title: "프레젠테이션 시청",
        video_lang_help: "원하는 언어를 위에서 선택하여 네이티브 오디오로 기관 프레젠테이션을 시청하세요.",
        footer_compliance: "국제 규정 준수 표준에 따라 설계된 아키텍처: GDPR(EU) • COPPA(미국) • UN(일반 논평 제25호 — 아동의 권리)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR 준수.",
        about_main_title: "BENEATH란 무엇인가요?",
        about_main_desc: "전화번호, 이메일 주소 또는 개인 정보를 공유하지 않고 비공개 통신을 지원하는 사이버 보안 도구입니다. 엔터테인먼트 메시징 서비스가 아닙니다.",
        about_transmit_title: "전송하되 저장하지 않음 (48 / 72시간)",
        about_transmit_desc: "메시지와 파일은 전달 후 인프라에서 삭제됩니다. 파일은 48~72시간 후에 만료되므로 사라지기 전에 다운로드하세요.",
        about_ideal_title: "적합한 대상:",
        about_item_sports: "<strong>스포츠 클럽:</strong> 다이렉트 및 보안 메시징.",
        about_item_schools: "<strong>학교:</strong> 개인 번호를 노출하지 않는 교사와 학부모 간의 소통.",
        about_item_companies: "<strong>기업 및 전문 서비스:</strong> 개인 연락처를 노출하지 않고 고객, 공급업체 또는 지원자와 문서를 기밀 교환."
    },
    zh: {
        lang_label: "语言：",
        tagline: "保持您的私密聊天真正私密",
        btn_home: "首页",
        btn_privacy: "关于我们",
        btn_compliance: "全球合规标准",
        btn_pricing: "定价与机构层级",
        btn_faq: "常见问题",
        btn_support: "高管支持与联系",
        cta_secure: "激活安全模式",
        video_header_badge: "在视频菜单中查找您的语言",
        video_preview_title: "观看演示",
        video_lang_help: "在上方选择您的首选语言，即可观看带有原生音频的机构演示。",
        footer_compliance: "架构设计符合国际合规标准：GDPR (欧盟) • COPPA (美国) • 联合国 (第25号一般性意见 — 儿童权利)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR 标准。",
        about_main_title: "什么是 BENEATH？",
        about_main_desc: "一款用于私人通信的网络安全工具，无需分享您的电话号码、电子邮箱地址或个人数据。它不是娱乐消息服务。",
        about_transmit_title: "传输，不存储（48 / 72 小时）",
        about_transmit_desc: "消息和文件在交付后会从基础设施中清除。文件将在 48 到 72 小时后过期。请在它们消失之前下载。",
        about_ideal_title: "理想适用于：",
        about_item_sports: "<strong>体育俱乐部：</strong> 直接且安全的通信。",
        about_item_schools: "<strong>学校：</strong> 教师与家长之间的沟通，无需暴露个人号码。",
        about_item_companies: "<strong>企业及专业服务：</strong> 与客户、供应商或候选人机密交换文件和数据，而不暴露个人联系方式。"
    },
    ja: {
        lang_label: "言語:",
        tagline: "プライベートなチャットを非公開に保つ",
        btn_home: "ホーム",
        btn_privacy: "私たちについて",
        btn_compliance: "グローバルコンプライアンス基準",
        btn_pricing: "価格設定と組織階層",
        btn_faq: "よくある質問",
        btn_support: "エグゼクティブサポート＆お問い合わせ",
        cta_secure: "セキュアモードを有効にする",
        video_header_badge: "動画メニューから言語を検索してください",
        video_preview_title: "プレゼンテーションを見る",
        video_lang_help: "上記でお好みの言語を選択して、ネイティブ音声付きの企業プレゼンテーションをご覧ください。",
        footer_compliance: "国際コンプライアンス基準に準拠して設計されたアーキテクチャ: GDPR (EU) • COPPA (米国) • 国連 (一般意見第25号 — 子どもの権利)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR準拠。",
        about_main_title: "BENEATHとは何ですか？",
        about_main_desc: "電話番号、メールアドレス、個人情報を共有せずにプライベートな通信を行うためのサイバーセキュリティツールです。エンターテインメント向けメッセージングサービスではありません。",
        about_transmit_title: "送信し、保存しない（48〜72時間）",
        about_transmit_desc: "メッセージとファイルは配信後にインフラから削除されます。ファイルは48〜72時間で期限切れになります。消える前にダウンロードしてください。",
        about_ideal_title: "主な用途：",
        about_item_sports: "<strong>スポーツクラブ：</strong> 直接的で安全なメッセージング。",
        about_item_schools: "<strong>学校：</strong> 個人の電話番号を公開せずに、教師と保護者間でコミュニケーション。",
        about_item_companies: "<strong>企業および専門サービス：</strong> 個人の連絡先を公開せずに、顧客、サプライヤー、候補者と機密文書やデータを交換。"
    },
    it: {
        lang_label: "Lingua:",
        tagline: "MANTIENI PRIVATE LE TUE CHAT PRIVATE",
        btn_home: "HOME",
        btn_privacy: "CHI SIAMO",
        btn_compliance: "STANDARD DI CONFORMITÀ GLOBALE",
        btn_pricing: "PREZZI E LIVELLI ISTITUZIONALI",
        btn_faq: "FAQ",
        btn_support: "SUPPORTO ESECUTIVO E CONTATTI",
        cta_secure: "ATTIVA MODALITÀ SICURA",
        video_header_badge: "CERCA LA TUA LINGUA NEL MENU VIDEO",
        video_preview_title: "GUARDA LA PRESENTAZIONE",
        video_lang_help: "Seleziona la tua lingua preferita sopra per guardare la presentazione istituzionale con audio nativo.",
        footer_compliance: "Architettura progettata in conformità agli standard di conformità internazionale: GDPR (UE) • COPPA (USA) • ONU (Commento generale n. 25 — Diritti dei bambini)",
        footer_copyright: "© 2026 BENEATH Technologies. | Conforme al GDPR.",
        about_main_title: "Cos'è BENEATH?",
        about_main_desc: "Uno strumento di cybersicurezza per la comunicazione privata senza condividere numero di telefono, e-mail o dati personali. Non è un servizio di messaggistica di intrattenimento.",
        about_transmit_title: "Trasmettere, non archiviare (48 / 72 ore)",
        about_transmit_desc: "Messaggi e file vengono eliminati dall'infrastruttura una volta consegnati. I file scadono dopo 48-72 ore. Scaricali prima che svaniscano.",
        about_ideal_title: "Ideale per:",
        about_item_sports: "<strong>Club Sportivi:</strong> Messaggistica diretta e sicura.",
        about_item_schools: "<strong>Scuole:</strong> Comunicazione tra insegnanti e genitori senza esporre numeri personali.",
        about_item_companies: "<strong>Aziende e Servizi Professionali:</strong> Scambio riservato di documenti e dati con clienti, fornitori o candidati senza esporre contatti personali."
    },
    hi: {
        lang_label: "भाषा:",
        tagline: "अपनी निजी चैट को निजी रखें",
        btn_home: "होम",
        btn_privacy: "हमारे बारे में",
        btn_compliance: "वैश्विक अनुपालन मानक",
        btn_pricing: "मूल्य निर्धारण और संस्थागत स्तर",
        btn_faq: "अक्सर पूछे जाने वाले प्रश्न",
        btn_support: "कार्यकारी सहायता और संपर्क",
        cta_secure: "सुरक्षित मोड सक्रिय करें",
        video_header_badge: "वीडियो मेनू में अपनी भाषा खोजें",
        video_preview_title: "प्रस्तुति देखें",
        video_lang_help: "मूल ऑडियो के साथ संस्थागत प्रस्तुति देखने के लिए ऊपर अपनी पसंदीदा भाषा चुनें।",
        footer_compliance: "अंतर्राष्ट्रीय अनुपालन मानकों के अनुसार डिज़ाइन की गई वास्तुकला: GDPR (EU) • COPPA (USA) • संयुक्त राष्ट्र (सामान्य टिप्पणी संख्या 25 — बच्चों के अधिकार)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR अनुcompliant。",
        about_main_title: "BENEATH क्या है?",
        about_main_desc: "बिना अपना फोन नंबर, ईमेल पता या व्यक्तिगत डेटा साझा किए निजी संचार के लिए एक साइबर सुरक्षा उपकरण। यह मनोरंजन मैसेजिंग सेवा नहीं है।",
        about_transmit_title: "ट्रांसमिट करें, स्टोर न करें (48 / 72 घंटे)",
        about_transmit_desc: "संदेश और फ़ाइलें डिलीवर होने के बाद बुनियादी ढांचे से हटा दी जाती हैं। फ़ाइलें 48 से 72 घंटों के बाद समाप्त हो जाती हैं। उनके गायब होने से पहले उन्हें डाउनलोड करें।",
        about_ideal_title: "इसके लिए आदर्श:",
        about_item_sports: "<strong>स्पोर्ट्स क्लब:</strong> प्रत्यक्ष और सुरक्षित मैसेजिंग।",
        about_item_schools: "<strong>स्कूल:</strong> व्यक्तिगत नंबरों को उजागर किए बिना शिक्षकों और माता-पिता के बीच संचार।",
        about_item_companies: "<strong>कंपनियां और पेशेवर सेवाएं:</strong> व्यक्तिगत संपर्क विवरण उजागर किए बिना ग्राहकों, आपूर्तिकर्ताओं या उम्मीदवारों के साथ दस्तावेजों और डेटा का गोपनीय आदान-प्रदान।"
    },
    ar: {
        lang_label: "اللغة:",
        tagline: "حافظ على سرية محادثاتك الخاصة",
        btn_home: "الرئيسية",
        btn_privacy: "معلومات عنا",
        btn_compliance: "معايير الامتثال العالمية",
        btn_pricing: "التسعير والمستويات المؤسسية",
        btn_faq: "الأسئلة الشائعة",
        btn_support: "الدعم التنفيذي والاتصال",
        cta_secure: "تفعيل الوضع الآمن",
        video_header_badge: "ابحث عن لغتك في قائمة الفيديو",
        video_preview_title: "شاهد العرض التقديمي",
        video_lang_help: "اختر لغتك المفضلة أعلاه لمشاهدة العرض التقديمي المؤسسي بالصوت الأصلي.",
        footer_compliance: "هندسة معمارية مصممة وفقاً لمعايير الامتثال الدولية: GDPR (الاتحاد الأوروبي) • COPPA (الولايات المتحدة) • الأمم المتحدة (التعليق العام رقم 25 — حقوق الأطفال)",
        footer_copyright: "© 2026 BENEATH Technologies. | متوافق مع GDPR.",
        about_main_title: "ما هو BENEATH؟",
        about_main_desc: "أداة أمن سيبراني للاتصال الخاص دون مشاركة رقم هاتفك أو بريدك الإلكتروني أو بياناتك الشخصية. إنها ليست خدمة رسائل ترفيهية.",
        about_transmit_title: "الإرسال وليس التخزين (48 / 72 ساعة)",
        about_transmit_desc: "يتم مسح الرسائل والملفات من البنية التحتية بمجرد تسليمها. تنتهي صلاحية الملفات بعد 48 إلى 72 ساعة. قم بتنزيلها قبل أن تختفي.",
        about_ideal_title: "مثالي لـ:",
        about_item_sports: "<strong>النوادي الرياضية:</strong> مراسلة مباشرة وآمنة.",
        about_item_schools: "<strong>المدارس:</strong> التواصل بين المعلمين وأولياء الأمور دون كشف الأرقام الشخصية.",
        about_item_companies: "<strong>الشركات والخدمات المهنية:</strong> تبادل المستندات والبيانات بسرية مع العملاء أو الموردين أو المرشحين دون الكشف عن تفاصيل الاتصال الشخصية."
    },
    tr: {
        lang_label: "Dil:",
        tagline: "ÖZEL SOHBETLERİNİZİ GİZLİ TUTUN",
        btn_home: "ANA SAYFA",
        btn_privacy: "HAKKIMIZDA",
        btn_compliance: "KÜRESEL UYUMLULUK STANDARTLARI",
        btn_pricing: "FİYATLANDIRMA VE KURUMSAL KATMANLAR",
        btn_faq: "SSS",
        btn_support: "YÖNETİCİ DESTEĞİ VE İLETİŞİM",
        cta_secure: "GÜVENLİ MODU ETKİNLEŞTİR",
        video_header_badge: "VİDEO MENÜSÜNDEN DİLİNİZİ ARAYIN",
        video_preview_title: "SUNUMU İZLE",
        video_lang_help: "Kurumsal sunumu orijinal sesle izlemek için yukarıdan tercih ettiğiniz dili seçin.",
        footer_compliance: "Uluslararası uyumluluk standartlarına uygun olarak tasarlanmış mimari: GDPR (AB) • COPPA (ABD) • BM (Genel Yorum No. 25 — Çocuk Hakları)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR Uyumlu.",
        about_main_title: "BENEATH Nedir?",
        about_main_desc: "Telefon numaranızı, e-posta adresinizi veya kişisel verilerinizi paylaşmadan özel iletişim kurmanızı sağlayan bir siber güvenlik aracıdır. Eğlence amaçlı bir mesajlaşma servisi değildir.",
        about_transmit_title: "İlet, depolama (48 / 72 saat)",
        about_transmit_desc: "Mesajlar ve dosyalar iletildikten sonra altyapıdan silinir. Dosyaların süresi 48 ila 72 saat sonra geçerliliğini yitirir. Kaybolmadan önce indirin.",
        about_ideal_title: "Şunlar için idealdir:",
        about_item_sports: "<strong>Spor Kulüpleri:</strong> Doğrudan ve güvenli mesajlaşma.",
        about_item_schools: "<strong>Okullar:</strong> Öğretmenler ve veliler arasında kişisel numaralar ifşa edilmeden iletişim.",
        about_item_companies: "<strong>Şirketler ve Profesyonel Hizmetler:</strong> Kişisel iletişim bilgileri açığa çıkmadan müşteriler, tedarikçiler veya adaylarla gizli belge ve veri değişimi."
    },
    ru: {
        lang_label: "Язык:",
        tagline: "СОХРАНЯЙТЕ СВОИ ЧАТЫ КОНФИДЕНЦИАЛЬНЫМИ",
        btn_home: "ГЛАВНАЯ",
        btn_privacy: "О НАС",
        btn_compliance: "ГЛОБАЛЬНЫЕ СТАНДАРТЫ СООТВЕТСТВИЯ",
        btn_pricing: "ЦЕНЫ И ИНСТИТУЦИОНАЛЬНЫЕ УРОВНИ",
        btn_faq: "ЧАСТО ЗАДАВАЕМЫЕ ВОПРОСЫ",
        btn_support: "РУКОВОДСТВО И ПОДДЕРЖКА",
        cta_secure: "АКТИВИРОВАТЬ ЗАЩИЩЕННЫЙ РЕЖИМ",
        video_header_badge: "НАЙДИТЕ СВОЙ ЯЗЫК В МЕНЮ ВИДЕО",
        video_preview_title: "СМОТРЕТЬ ПРЕЗЕНТАЦИЮ",
        video_lang_help: "Выберите предпочитаемый язык выше, чтобы посмотреть презентацию компании с оригинальным звуком.",
        footer_compliance: "Архитектура разработана в соответствии с международными стандартами соответствия: GDPR (ЕС) • COPPA (США) • ООН (Замечание общего порядка № 25 — Права детей)",
        footer_copyright: "© 2026 BENEATH Technologies. | Соответствует GDPR.",
        about_main_title: "Что такое BENEATH?",
        about_main_desc: "Инструмент кибербезопасности для конфиденциальной связи без раскрытия номера телефона, электронной почты или личных данных. Это не развлекательный мессенджер.",
        about_transmit_title: "Передавать, а не хранить (48 / 72 часа)",
        about_transmit_desc: "Сообщения и файлы удаляются из инфраструктуры после доставки. Срок действия файлов истекает через 48–72 часа. Загрузите их, пока они не исчезли.",
        about_ideal_title: "Идеально подходит для:",
        about_item_sports: "<strong>Спортивных клубов:</strong> Прямой и безопасный обмен сообщениями.",
        about_item_schools: "<strong>Школ:</strong> Связь между учителями и родителями без раскрытия личных номеров.",
        about_item_companies: "<strong>Компаний и профессиональных услуг:</strong> Конфиденциальный обмен документами и данными с клиентами, поставщиками или кандидатами без раскрытия личных контактов."
    },
    sv: {
        lang_label: "Språk:",
        tagline: "HÅLL DINA PRIVATA CHATTAR PRIVATA",
        btn_home: "HEM",
        btn_privacy: "OM OSS",
        btn_compliance: "GLOBALA EFTERLEVNADSSTANDARDER",
        btn_pricing: "PRISSÄTTNING & INSTITUTIONELLA NIVÅER",
        btn_faq: "FAQ",
        btn_support: "EXECUTIVE SUPPORT & KONTAKT",
        cta_secure: "AKTIVERA SÄKERT LÄGE",
        video_header_badge: "SÖK DITT SPRÅK I VIDEOMENYN",
        video_preview_title: "SE PRESENTATION",
        video_lang_help: "Välj ditt föredragna språk ovan för att titta på den institutionella presentationen med originalljud.",
        footer_compliance: "Arkitektur utformad i enlighet med internationella efterlevnadsstandarder: GDPR (EU) • COPPA (USA) • FN (Allmän kommentar nr 25 — Barnets rättigheter)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR-kompatibel.",
        about_main_title: "Vad är BENEATH?",
        about_main_desc: "Ett cybersäkerhetsverktyg för privat kommunikation utan att dela ditt telefonnummer, e-postadress eller personliga uppgifter. Det är inte en underhållningsmeddelandetjänst.",
        about_transmit_title: "Överför, lagra inte (48 / 72 timmar)",
        about_transmit_desc: "Meddelanden och filer rensas från infrastrukturen när de har levererats. Filer upphör att gälla efter 48 till 72 timmar. Ladda ner dem innan de försvinner.",
        about_ideal_title: "Perfekt för:",
        about_item_sports: "<strong>Sportklubbar:</strong> Direkt och säker meddelandehantering.",
        about_item_schools: "<strong>Skolor:</strong> Kommunikation mellan lärare och föräldrar utan att avslöja personliga nummer.",
        about_item_companies: "<strong>Företag och Professionella Tjänster:</strong> Konfidentiellt utbyte av dokument och data med kunder, leverantörer eller kandidater utan att avslöja personliga kontaktuppgifter."
    },
    nl: {
        lang_label: "Taal:",
        tagline: "HOUD UW PRIVÉ-CHATS PRIVÉ",
        btn_home: "HOME",
        btn_privacy: "OVER ONS",
        btn_compliance: "WERELDWIJDE NALEVINGSNORMEN",
        btn_pricing: "PRIJZEN EN INSTITUTIONELE NIVEAUS",
        btn_faq: "FAQ",
        btn_support: "EXECUTIVE ONDERSTEUNING & CONTACT",
        cta_secure: "VEILIGE MODUS ACTIVEREN",
        video_header_badge: "ZOEK UW TAAL IN HET VIDEOMENU",
        video_preview_title: "BEKIJK PRESENTATIE",
        video_lang_help: "Selecteer hierboven uw voorkeurstaal om de institutionelle presentatie met originele audio te bekijken.",
        footer_compliance: "Architectuur ontworpen in overeenstemming met internationale nalevingsnormen: GDPR (EU) • COPPA (VS) • VN (Algemeen commentaar nr. 25 — Rechten van het kind)",
        footer_copyright: "© 2026 BENEATH Technologies. | GDPR-compliant.",
        about_main_title: "Wat is BENEATH?",
        about_main_desc: "Een cybersecurity-tool voor privécommunicatie zonder je telefoonnummer, e-mailadres of persoonlijke gegevens te delen. Het is geen ontspanningsberichtendienst.",
        about_transmit_title: "Verzenden, niet opslaan (48 / 72 uur)",
        about_transmit_desc: "Berichten en bestanden worden na bezorging uit de infrastructuur gewist. Bestanden verlopen na 48 tot 72 uur. Download ze voordat ze verdwijnen.",
        about_ideal_title: "Ideaal voor:",
        about_item_sports: "<strong>Sportclubs:</strong> Directe en veilige berichtenuitwisseling.",
        about_item_schools: "<strong>Scholen:</strong> Communicatie tussen leraren en ouders zonder persoonlijke nummers prijs te geven.",
        about_item_companies: "<strong>Bedrijven & Professionele Diensten:</strong> Vertrouwelijke uitwisseling van documenten en gegevens met klanten, leveranciers of kandidaten zonder persoonlijke contactgegevens te onthullen."
    }
};

function cambiarIdioma(lang) {
    if (!DICTIONARY[lang]) return;
    
    localStorage.setItem('sipv_lang', lang);
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (DICTIONARY[lang][key]) {
            el.innerHTML = DICTIONARY[lang][key];
        }
    });
}

document.addEventListener("DOMContentLoaded", () => {
    const langGuardado = localStorage.getItem('sipv_lang') || 'en';
    cambiarIdioma(langGuardado);
    
    const selector = document.getElementById('cambiador-idioma');
    if (selector) {
        selector.value = langGuardado;
        selector.addEventListener('change', (e) => cambiarIdioma(e.target.value));
    }
});